console.info("ჩემს შესახებ");
let FirstName = "Tika";
let LastName = "Nazghaidze";
let MyAge = "26";
let MyPhone = "599997551";
let Email ="nazgaidzetika@gmail.com";
let HavePet = true;
console.log(FirstName);
console.log(LastName);
console.log(MyAge);
console.log(MyPhone);
console.log(Email);
console.log(HavePet);
console.log( `Hello ,i am  ${FirstName} ${LastName}`)

let FavActress ="Julia Roberts";
let HerAge ="57";
let IsFrom ="USA";
console.log(FavActress);
console.log(HerAge);
console.log(IsFrom);
console.warn("სახელის შეცვლა");
FavActress = "Angelina Jolie";
console.log(FavActress);
const Film ="Mr and Mrs Smiths";
console.log(Film);
let a = 26;
let b = 57;
console.log(a+b);
console.log(a-b);
console.log(a*b);
console.log(a/b);
